#!/usr/bin/env python3
"""
Visualization script for electrostatic solver results
Reads CSV files generated by test_electrostatic.cpp and creates plots
"""

import numpy as np
import matplotlib.pyplot as plt
import os
from pathlib import Path

def load_csv(filename):
    """Load CSV file as numpy array"""
    if not os.path.exists(filename):
        print(f"Warning: {filename} not found")
        return None
    return np.loadtxt(filename, delimiter=',')

def main():
    print("=" * 60)
    print("Electrostatic Solver - Visualization")
    print("=" * 60)
    print()
    
    # Load data files
    print("Loading CSV files...")
    
    potential = load_csv('potential.csv')
    Ex = load_csv('Ex.csv')
    Ey = load_csv('Ey.csv')
    E_magnitude = load_csv('E_magnitude.csv')
    energy_density = load_csv('energy_density.csv')
    
    if potential is None:
        print("Error: potential.csv not found. Run test_electrostatic first.")
        return 1
    
    print("✓ All files loaded successfully\n")
    
    # Create figure with subplots
    fig = plt.figure(figsize=(16, 10))
    
    # ========== Potential Field ==========
    ax1 = plt.subplot(2, 3, 1)
    im1 = ax1.contourf(potential, levels=20, cmap='RdYlBu_r')
    ax1.set_title('Electric Potential φ (V)', fontsize=12, fontweight='bold')
    ax1.set_xlabel('x (grid points)')
    ax1.set_ylabel('y (grid points)')
    plt.colorbar(im1, ax=ax1, label='Potential (V)')
    
    # ========== Ex Component ==========
    ax2 = plt.subplot(2, 3, 2)
    if Ex is not None:
        im2 = ax2.contourf(Ex, levels=20, cmap='seismic')
        ax2.set_title('Electric Field Ex (V/m)', fontsize=12, fontweight='bold')
        ax2.set_xlabel('x (grid points)')
        ax2.set_ylabel('y (grid points)')
        plt.colorbar(im2, ax=ax2, label='Ex (V/m)')
    
    # ========== Ey Component ==========
    ax3 = plt.subplot(2, 3, 3)
    if Ey is not None:
        im3 = ax3.contourf(Ey, levels=20, cmap='seismic')
        ax3.set_title('Electric Field Ey (V/m)', fontsize=12, fontweight='bold')
        ax3.set_xlabel('x (grid points)')
        ax3.set_ylabel('y (grid points)')
        plt.colorbar(im3, ax=ax3, label='Ey (V/m)')
    
    # ========== Field Magnitude ==========
    ax4 = plt.subplot(2, 3, 4)
    if E_magnitude is not None:
        im4 = ax4.contourf(E_magnitude, levels=20, cmap='hot')
        ax4.set_title('Electric Field Magnitude |E| (V/m)', fontsize=12, fontweight='bold')
        ax4.set_xlabel('x (grid points)')
        ax4.set_ylabel('y (grid points)')
        plt.colorbar(im4, ax=ax4, label='|E| (V/m)')
    
    # ========== Energy Density ==========
    ax5 = plt.subplot(2, 3, 5)
    if energy_density is not None:
        im5 = ax5.contourf(energy_density, levels=20, cmap='viridis')
        ax5.set_title('Energy Density u = ½εE² (J/m³)', fontsize=12, fontweight='bold')
        ax5.set_xlabel('x (grid points)')
        ax5.set_ylabel('y (grid points)')
        plt.colorbar(im5, ax=ax5, label='u (J/m³)')
    
    # ========== Vector Field ==========
    ax6 = plt.subplot(2, 3, 6)
    if Ex is not None and Ey is not None:
        # Create a coarser grid for vector field visualization
        step = 2
        Y, X = np.mgrid[0:Ex.shape[0]:step, 0:Ex.shape[1]:step]
        
        # Plot potential as background
        im6 = ax6.contourf(potential, levels=15, cmap='RdYlBu_r', alpha=0.6)
        
        # Overlay electric field vectors
        ax6.quiver(X, Y, Ex[::step, ::step], Ey[::step, ::step], 
                  color='black', scale=5, width=0.003)
        
        ax6.set_title('Electric Field Vectors', fontsize=12, fontweight='bold')
        ax6.set_xlabel('x (grid points)')
        ax6.set_ylabel('y (grid points)')
        plt.colorbar(im6, ax=ax6, label='Potential (V)')
    
    plt.tight_layout()
    
    # Save figure
    output_file = 'electrostatic_solution.png'
    plt.savefig(output_file, dpi=150, bbox_inches='tight')
    print(f"✓ Figure saved to: {output_file}\n")
    
    # Print statistics
    print("=" * 60)
    print("Data Statistics")
    print("=" * 60)
    print(f"\nPotential Field:")
    print(f"  Min: {potential.min():.6f} V")
    print(f"  Max: {potential.max():.6f} V")
    print(f"  Mean: {potential.mean():.6f} V")
    print(f"  Range: {potential.max() - potential.min():.6f} V")
    
    if E_magnitude is not None:
        print(f"\nElectric Field Magnitude:")
        print(f"  Min: {E_magnitude.min():.6e} V/m")
        print(f"  Max: {E_magnitude.max():.6e} V/m")
        print(f"  Mean: {E_magnitude.mean():.6e} V/m")
    
    if energy_density is not None:
        print(f"\nEnergy Density:")
        print(f"  Min: {energy_density.min():.6e} J/m³")
        print(f"  Max: {energy_density.max():.6e} J/m³")
        print(f"  Mean: {energy_density.mean():.6e} J/m³")
        print(f"  Total (approx): {energy_density.sum() * 0.01:.6e} J")  # dx*dy = 0.1*0.1 = 0.01
    
    print("\n" + "=" * 60)
    print("Visualization complete!")
    print("=" * 60)
    
    # Display plot
    plt.show()
    
    return 0

if __name__ == '__main__':
    import sys
    sys.exit(main())
